CREATE TABLESPACE tbs_perm_mv_01 DATAFILE 'tbs_perm_mv_01.dat' SIZE 20M;

CREATE TEMPORARY TABLESPACE tbs_temp_mv_01 TEMPFILE 'tbs_temp_mv_01.dbf' SIZE 5M;

CREATE USER mv
  IDENTIFIED BY 123
  DEFAULT TABLESPACE tbs_perm_mv_01
  TEMPORARY TABLESPACE tbs_temp_mv_01
  QUOTA 20M on tbs_perm_mv_01;

GRANT CREATE SESSION TO mv;
GRANT CREATE TABLE TO mv;
GRANT CREATE VIEW TO mv;
GRANT CREATE ANY trigger TO mv;
GRANT CREATE ANY procedure TO mv;
GRANT CREATE SEQUENCE TO mv;
GRANT CREATE SYNONYM TO mv;