INSERT INTO MV.CATEGORIA (CD_CATEGORIA, DS_CATEGORIA , NR_PERCENTUAL ) VALUES (1,'Eletrodomestico', 10);
INSERT INTO MV.CATEGORIA (CD_CATEGORIA, DS_CATEGORIA , NR_PERCENTUAL ) VALUES (2,'Eletronico', 20);
INSERT INTO MV.CATEGORIA (CD_CATEGORIA, DS_CATEGORIA , NR_PERCENTUAL ) VALUES (3,'Cozinha', 30);
INSERT INTO MV.CATEGORIA (CD_CATEGORIA, DS_CATEGORIA , NR_PERCENTUAL ) VALUES (4,'Cama', 40);
