INSERT INTO PROJETOMV.CATEGORIA (ID_CATEGORIA , CD_CATEGORIA, DS_CATEGORIA , NR_PERCENTUAL ) VALUES (1,1,'Eletrodomestico', 10);
INSERT INTO PROJETOMV.CATEGORIA (ID_CATEGORIA , CD_CATEGORIA, DS_CATEGORIA , NR_PERCENTUAL ) VALUES (2,2,'Cozinha', 20);
INSERT INTO PROJETOMV.CATEGORIA (ID_CATEGORIA , CD_CATEGORIA, DS_CATEGORIA , NR_PERCENTUAL ) VALUES (3,3,'Eletronico', 30);
